name: Autograding Tests

on:
  push:
    branches:
      - main
      - master

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Fetch test file from private repository
      run: |
        curl -H "Authorization: token ${{ secrets.TEST_ACCESS_TOKEN }}" \
             -H "Accept: application/vnd.github.v3.raw" \
             -o test_mechanical.py \
             https://api.github.com/repos/${{ secrets.TEST_REPO_OWNER }}/mechanical-tests-private/contents/numpy-ufunc/test_mechanical.py
      
    - name: Q1-Q2 Von Mises & Projectile (20 points)
      run: |
        echo "Testing Q1-Q2..."
        pytest test_mechanical.py::TestQ1VonMisesStress -v
        pytest test_mechanical.py::TestQ2ProjectileTrajectory -v
        echo "✅ Q1-Q2 PASSED"
        
    - name: Q3-Q4 Forces & Thermal (20 points)
      run: |
        echo "Testing Q3-Q4..."
        pytest test_mechanical.py::TestQ3ForceResultant -v
        pytest test_mechanical.py::TestQ4ThermalExpansion -v
        echo "✅ Q3-Q4 PASSED"
        
    - name: Q5-Q6 Angular & Beam (20 points)
      run: |
        echo "Testing Q5-Q6..."
        pytest test_mechanical.py::TestQ5AngularVelocity -v
        pytest test_mechanical.py::TestQ6BeamDeflection -v
        echo "✅ Q5-Q6 PASSED"
        
    - name: Q7-Q8 Velocity & Power (20 points)
      run: |
        echo "Testing Q7-Q8..."
        pytest test_mechanical.py::TestQ7VelocityComponents -v
        pytest test_mechanical.py::TestQ8PowerTorque -v
        echo "✅ Q7-Q8 PASSED"
        
    - name: Q9-Q10 Spring & Damping (20 points)
      run: |
        echo "Testing Q9-Q10..."
        pytest test_mechanical.py::TestQ9SpringSystem -v
        pytest test_mechanical.py::TestQ10DampedOscillation -v
        echo "✅ Q9-Q10 PASSED"
        
    - name: Calculate Score
      if: always()
      run: |
        echo "========================================="
        echo "GRADING SUMMARY"
        echo "========================================="
        echo "Check marks above show which sections passed"
        echo "Each section worth 20 points"
        echo "5 sections = 100 points total"
        echo "========================================="
