name: Autograding Tests

on:
  push:
    branches:
      - main
      - master

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Fetch test file from private repository
      run: |
        curl -H "Authorization: token ${{ secrets.TEST_ACCESS_TOKEN }}" \
             -H "Accept: application/vnd.github.v3.raw" \
             -o test_mechanical.py \
             https://api.github.com/repos/${{ secrets.TEST_REPO_OWNER }}/mechanical-tests-private/contents/numpy-ufunc/test_mechanical.py
      
    - name: Verify test file exists
      run: |
        if [ ! -f test_mechanical.py ]; then
          echo "ERROR: Test file not downloaded!"
          exit 1
        fi
        echo "✅ Test file downloaded successfully"
        
    - name: Q1-Q2 Von Mises & Projectile (20 points)
      run: |
        echo "================================================"
        echo "Testing Q1-Q2: Von Mises & Projectile (20 pts)"
        echo "================================================"
        pytest test_mechanical.py::TestQ1VonMisesStress -v --tb=short
        pytest test_mechanical.py::TestQ2ProjectileTrajectory -v --tb=short
        echo "✅ Q1-Q2 PASSED - 20/20 points"
        
    - name: Q3-Q4 Forces & Thermal (20 points)
      run: |
        echo "================================================"
        echo "Testing Q3-Q4: Forces & Thermal (20 pts)"
        echo "================================================"
        pytest test_mechanical.py::TestQ3ForceResultant -v --tb=short
        pytest test_mechanical.py::TestQ4ThermalExpansion -v --tb=short
        echo "✅ Q3-Q4 PASSED - 20/20 points"
        
    - name: Q5-Q6 Angular & Beam (20 points)
      run: |
        echo "================================================"
        echo "Testing Q5-Q6: Angular & Beam (20 pts)"
        echo "================================================"
        pytest test_mechanical.py::TestQ5AngularVelocity -v --tb=short
        pytest test_mechanical.py::TestQ6BeamDeflection -v --tb=short
        echo "✅ Q5-Q6 PASSED - 20/20 points"
        
    - name: Q7-Q8 Velocity & Power (20 points)
      run: |
        echo "================================================"
        echo "Testing Q7-Q8: Velocity & Power (20 pts)"
        echo "================================================"
        pytest test_mechanical.py::TestQ7VelocityComponents -v --tb=short
        pytest test_mechanical.py::TestQ8PowerTorque -v --tb=short
        echo "✅ Q7-Q8 PASSED - 20/20 points"
        
    - name: Q9-Q10 Spring & Damping (20 points)
      run: |
        echo "================================================"
        echo "Testing Q9-Q10: Spring & Damping (20 pts)"
        echo "================================================"
        pytest test_mechanical.py::TestQ9SpringSystem -v --tb=short
        pytest test_mechanical.py::TestQ10DampedOscillation -v --tb=short
        echo "✅ Q9-Q10 PASSED - 20/20 points"
        
    - name: Final Score Summary
      if: success()
      run: |
        echo ""
        echo "================================================"
        echo "           ✅ ALL TESTS PASSED! ✅"
        echo "================================================"
        echo "Q1-Q2: Von Mises & Projectile    20/20 ✅"
        echo "Q3-Q4: Forces & Thermal          20/20 ✅"
        echo "Q5-Q6: Angular & Beam            20/20 ✅"
        echo "Q7-Q8: Velocity & Power          20/20 ✅"
        echo "Q9-Q10: Spring & Damping         20/20 ✅"
        echo "=========================================="
        echo "TOTAL SCORE: 100/100 🎉"
        echo "=========================================="
```

---

## **Why This Works Better**

**Problems with autograding-command-grader:**
- ❌ Reports false failures (exit code 1)
- ❌ Can't handle `&&` properly
- ❌ Complex integration issues

**Benefits of simple workflow:**
- ✅ Tests actually run and pass
- ✅ Clear visual feedback (green ✅ or red ❌)
- ✅ Each step shows points
- ✅ No reporter integration problems
- ✅ Students can see exactly which tests pass/fail

---

## **How to Grade with This Workflow**

### **For You (Instructor):**

1. Go to student repository
2. Click **Actions** tab
3. Look at latest workflow run
4. Count green checkmarks:
```
✅ Q1-Q2: 20 points
✅ Q3-Q4: 20 points  
✅ Q5-Q6: 20 points
✅ Q7-Q8: 20 points
✅ Q9-Q10: 20 points
-------------------
Total: 100 points
