name: Autograding Tests

on:
  push:
    branches:
      - main
      - master

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Fetch test file from private repository
      run: |
        curl -H "Authorization: token ${{ secrets.TEST_ACCESS_TOKEN }}" \
             -H "Accept: application/vnd.github.v3.raw" \
             -o test_mechanical.py \
             https://api.github.com/repos/${{ secrets.TEST_REPO_OWNER }}/mechanical-tests-private/contents/numpy-ufunc/test_mechanical.py
        
    - name: DEBUG - Verify test file downloaded
      run: |
        echo "=== Checking if test file exists ==="
        ls -lh test_mechanical.py
        echo ""
        echo "=== File size ==="
        wc -l test_mechanical.py
        echo ""
        echo "=== First 30 lines of test file ==="
        head -30 test_mechanical.py
        echo ""
        echo "=== Class names in file ==="
        grep -n "^class Test" test_mechanical.py
        echo ""
        
    - name: DEBUG - Try importing test file
      run: |
        echo "=== Testing if test file can be imported ==="
        python -c "import test_mechanical; print('✅ Test file imports successfully')" || echo "❌ Import failed"
        
    - name: DEBUG - Check mechanical_problems.py
      run: |
        echo "=== Checking mechanical_problems.py ==="
        ls -lh mechanical_problems.py
        head -20 mechanical_problems.py
        echo ""
        echo "=== Checking for 'pass' statements ==="
        grep -n "pass" mechanical_problems.py || echo "No pass statements found"
        
    - name: DEBUG - Try importing mechanical_problems
      run: |
        echo "=== Testing if mechanical_problems can be imported ==="
        python -c "from mechanical_problems import von_mises_stress; print('✅ mechanical_problems imports successfully')" || echo "❌ Import failed"
        
    - name: DEBUG - List available tests
      run: |
        echo "=== Collecting available tests ==="
        pytest test_mechanical.py --collect-only
        
    - name: Q1-Q2 Von Mises & Projectile (20 points)
      run: |
        echo "================================================"
        echo "Testing Q1-Q2: Von Mises & Projectile (20 pts)"
        echo "================================================"
        pytest test_mechanical.py::TestQ1VonMisesStress -v --tb=short
        pytest test_mechanical.py::TestQ2ProjectileTrajectory -v --tb=short
        echo "✅ Q1-Q2 PASSED - 20/20 points"
        
    - name: Q3-Q4 Forces & Thermal (20 points)
      run: |
        echo "================================================"
        echo "Testing Q3-Q4: Forces & Thermal (20 pts)"
        echo "================================================"
        pytest test_mechanical.py::TestQ3ForceResultant -v --tb=short
        pytest test_mechanical.py::TestQ4ThermalExpansion -v --tb=short
        echo "✅ Q3-Q4 PASSED - 20/20 points"
        
    - name: Q5-Q6 Angular & Beam (20 points)
      run: |
        echo "================================================"
        echo "Testing Q5-Q6: Angular & Beam (20 pts)"
        echo "================================================"
        pytest test_mechanical.py::TestQ5AngularVelocity -v --tb=short
        pytest test_mechanical.py::TestQ6BeamDeflection -v --tb=short
        echo "✅ Q5-Q6 PASSED - 20/20 points"
        
    - name: Q7-Q8 Velocity & Power (20 points)
      run: |
        echo "================================================"
        echo "Testing Q7-Q8: Velocity & Power (20 pts)"
        echo "================================================"
        pytest test_mechanical.py::TestQ7VelocityComponents -v --tb=short
        pytest test_mechanical.py::TestQ8PowerTorque -v --tb=short
        echo "✅ Q7-Q8 PASSED - 20/20 points"
        
    - name: Q9-Q10 Spring & Damping (20 points)
      run: |
        echo "================================================"
        echo "Testing Q9-Q10: Spring & Damping (20 pts)"
        echo "================================================"
        pytest test_mechanical.py::TestQ9SpringSystem -v --tb=short
        pytest test_mechanical.py::TestQ10DampedOscillation -v --tb=short
        echo "✅ Q9-Q10 PASSED - 20/20 points"
        
    - name: Final Score Summary
      if: success()
      run: |
        echo ""
        echo "================================================"
        echo "           ✅ ALL TESTS PASSED! ✅"
        echo "================================================"
        echo "Q1-Q2: Von Mises & Projectile    20/20 ✅"
        echo "Q3-Q4: Forces & Thermal          20/20 ✅"
        echo "Q5-Q6: Angular & Beam            20/20 ✅"
        echo "Q7-Q8: Velocity & Power          20/20 ✅"
        echo "Q9-Q10: Spring & Damping         20/20 ✅"
        echo "=========================================="
        echo "TOTAL SCORE: 100/100 🎉"
        echo "=========================================="
